name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Authenticate on AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ASIA6LGBAVWTOKZPSJUI
        aws-secret-access-key: e50li8Wj6u5RYOB+D/buHmFUn7+YBIkR3bg3mZhs
        aws-region: us-east-1

    - name: Build Function
      run: sam build --use-container
   
